<a href="https://colab.research.google.com/github/Hyunfor/2023_HNU_PythonClass/blob/master/23_05_02_~_%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%82%AC%EC%9D%B4%EC%96%B8%EC%8A%A4_%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EC%88%98%EC%97%85_9(8%EC%9E%A5)_~_10_(_9%EC%9E%A5_%EC%99%84%2C_10%EC%9E%A5_%EC%A7%84%ED%96%89%2C_11%EC%9E%A5_%EC%A7%84%ED%96%89).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

8장


In [ ]:
# 딕셔너리 장점 
# 어떤 자료형도 받을 수 있다.
# 튜플은 보안상의 이유로 따로 둠

# 리스트와 튜플은 순서자료형
phone_num_list = {}
phone_num_list["전우치"] = "010-2233-4455"
print(phone_num_list)

phone_num_list["도사협회"] = "01-1133-4455"
phone_num_list["빌런협회"] = "04-7733-4455"
print(phone_num_list)

# 리스트에서 인덱스, 딕셔너리에서는 키가 있어야 값을 찾을 수 있다.
# 모든 키를 출력하려면 keys()라는 메소드를 사용
# 반면 딕셔너리에서 사용되는 모든 값을 출력하려면 values()를 사용.
# 딕셔너리 내부의 모든 값을 출력하려면 items()를 사용
# items()를 쓰면 튜플로 출력 (출력된 값)
# Key()는 [(출력된 값), (출력된 값)]
for name, phone_num in phone_num_list.items():
    print(name,':',phone_num)

{'전우치': '010-2233-4455'}
{'전우치': '010-2233-4455', '도사협회': '01-1133-4455', '빌런협회': '04-7733-4455'}
전우치 : 010-2233-4455
도사협회 : 01-1133-4455
빌런협회 : 04-7733-4455


In [ ]:
person_dic = {'Name': "홍길동", 'Age': 27, 'Class': "초급"}
print(person_dic['Name']) # 딕셔너리의 Name키로 값을 조회
print(person_dic['Age']) # 딕셔너리의 Age키로 값을 조회
print(person_dic['Class'])

홍길동
27
초급


In [ ]:
def sum(a, b): # 일반적인 함수문
    return a+b
print(sum(3,4))

sum = lambda a,b : a+b # lambda함수로 일반적인 함수 코드를 간결하게 만들 수 있음.
print(sum(3,4))

7
7


In [ ]:
f = lambda x : x**2
f(3)

9

In [ ]:
f = lambda x : x/2
f(4)


2.0

In [ ]:
even_power = lambda x : x**2 if x%2 == 0 else x
print(even_power(2))
print(even_power(3))

4
3


In [ ]:
# 심화문제 8.3 한번 풀어보기
# 학번, 이름, 전화번호의 3쌍의 요소를 가지는 student_tup라는 튜플이 존재

# 1) 튜플을 수정하여 {학번 : [이름, 전화번호]}의 쌍으로 이루어진 딕셔너리를 만들어서 출력

# 2) 학생의 학번을 입력받아서 이름과 전화번호를 출력하는 학사 정보 프로그램을 작성

# 3) student_tup의 마지막 항목으로 직전학기 학점을 추가. 세 학생의 학점은 각각 4.3, 3.9, 4.25이다. 
# 이를 바탕으로 딕셔너리를 만들어 학생 정보를 출력하라

# 4) 3)의 정보를 이용하여 for 반보문과 인덱싱을 통해서 세 학생의 학점 평균값을 다음과 같이 출력하라.

9장

In [ ]:
# 문자열도 순서자료형 - > 인덱스를 가지고 있다 & 반복문에 사용가능
# split() - > 문자열 분리
# join() - > 문자열 합치기
# replace() - > 문자열 변경
# strip() - > 공백 제거거

In [ ]:
s = 'www.booksr.co.kr'
s.find('.kr')

13

In [ ]:
s = 'www.booksr.co.kr'
s.find('x')

-1

In [ ]:
s = 'www.booksr.co.kr'
print(s.index('.kr'))

13


In [ ]:
s = 'www.booksr.co.kr'
print(s.index('x'))

ValueError: ignored

In [ ]:
# LAB 9-2
# 트위터 메시지 처리의 단어 추출
t = "There's a reason some people are working to make it harder to vote, especially for people of color. It's because when we show up, things change."
length = len(t.split(' '))
print('world count:', length)

world count: 26


In [ ]:
# 9.7 워드클라우드 내용은 스스로 학습
# 9.8 정규표현식 내용은 프로젝트 진행시 필요시 학습

In [ ]:
# 심화문제 9.1 9.5, 9.6 집에서 해보기

In [ ]:
# 심화문제 9.1
# 영문 이름을 입력받은 후 중간 이름을 출력하라
name = input("영문 이름을 입력하세요: ")
names_list = name.split()  # 공백을 기준으로 문자열을 단어 단위로 분리합니다.
num_names = len(names_list)  # 입력된 이름의 단어 개수를 구합니다.

# 입력된 이름이 두 개 이상의 단어로 이루어져 있다면 중간 단어를 출력합니다.
if num_names >= 2:
    middle_index = num_names // 2  # 중간 단어의 인덱스를 계산합니다.
    middle_name = names_list[middle_index]  # 중간 단어를 가져옵니다.
    print("중간 이름은", middle_name, "입니다.")
else:
    print("입력된 이름이 너무 짧습니다.")

영문 이름을 입력하세요: jon smths meguel
중간 이름은 smths 입니다.


In [ ]:
# 심화문제 9.5
# s = Korea is awesome! I REALLY LOVE KOREA.
# Korea가 몇번 나타나는가 출력하라. 이때 KOREA, Korea와 korea는 같은 문자열로 간주한다.
s = "Korea is awesome! I REALLY LOVE KOREA."
count = s.lower().count("korea")  # 대소문자를 구분하지 않고 "Korea"가 몇 번 나타나는지 계산합니다.
print("Korea가 총", count, "번 나타납니다.")

Korea가 총 2 번 나타납니다.


In [ ]:
# 심화문제 9.6
# 문장에 'English = 98'와 같이 과목점수가 저장되어 있다. 이문장을 분석하여 숫자로 이루어진 점수를 읽어서 합과 평균점수를 구하라
# 문장 s : English = 89, Science = 90, Math = 92, History = 80.
# 총점 : 351
# 평균점수 87.75
s = "English = 89, Science = 90, Math = 92, History = 80."
scores = []  # 점수를 저장할 리스트를 초기화합니다.
for item in s.split(","):  # 쉼표를 기준으로 문자열을 분리합니다.
    score = item.split("=")[-1].strip()  # 등호를 기준으로 문자열을 분리하여 숫자를 추출합니다.
    scores.append(int(score))  # 추출한 숫자를 정수형으로 변환하여 리스트에 추가합니다.
total = sum(scores)  # 총점을 계산합니다.
average = total / len(scores)  # 평균점수를 계산합니다.
print("총점:", total)
print("평균점수:", round(average, 2))

ValueError: ignored

In [ ]:
s = "English = 89, Science = 90, Math = 92, History = 80."
scores = []
for item in s.split(","):
    score = item.split("=")[-1].strip()
    scores.append(float(score))  # 정수 대신 실수로 변환합니다.
total = sum(scores)
average = total / len(scores)
print("총점:", total)
print("평균점수:", round(average, 2))

총점: 351.0
평균점수: 87.75


10장
numpy

In [ ]:
# numpy의 핵심적인 객체는 다차원 배열
# 2차원 배열(테이블)을 넘파이를 이용해서 생성
# 배열의 각 요소는 index라 불리는 정수들로 참조
# 넘파이에서 차원은 axis 축 이라고도 함
# 행이 0, 축이 1

In [ ]:
import numpy as np

In [ ]:
mid_scores = np.array([10, 20, 30])
final_scores = np.array([60, 70, 80])
total = mid_scores + final_scores
print('시험성적의 합계 : ', total) # 각 요소별 합계가 나타난다
print(type(mid_scores))
print('시험성적의 평균 : ', total/2) # 모든 요소를 2로 나눈다
print(type(final_scores))

시험성적의 합계 :  [ 70  90 110]
<class 'numpy.ndarray'>
시험성적의 평균 :  [35. 45. 55.]
<class 'numpy.ndarray'>


In [ ]:
a = np.array([1, 2, 3])
print(a.shape)# 객체의 형태
print(a.ndim) # 객채의 차원
print(a.dtype) # 객체의 내부 자료형
print(a.itemsize) # 객체 내부 자료형이 차지하는 메모리 크기
print(a.size) # 객체의 전체 크기(항목 수수)

(3,)
1
int64
8
3


In [ ]:
# 넘파이의 배열, broadcasting브로드캐스팅이라 함함

In [ ]:
# LAB10-2 해보기
# 넘파이를 이용하여 다수의 인원에 대해 BMI 계싼을 효율적으로 적용하자
# 키를 저장하는 리스트 heights, 다른 하나는 몸무게를 저장하는 weights
# BMI를 한번에 계산 할 수 있는 방법은 ? 
heights = [1.83, 1.76, 1.69, 1.86, 1.77, 1.73]
weights = [86, 74, 59, 95, 80, 68]

np_heights = np.array(heights)
np_weights = np.array(weights)

bmi = np_heights/(np_heights**2)
print('대상자들의 키: ', np_heights)
print('대상자들의 몸무게: ', np_weights)
print('대상자들의 BMI')
print(bmi)

대상자들의 키:  [1.83 1.76 1.69 1.86 1.77 1.73]
대상자들의 몸무게:  [86 74 59 95 80 68]
대상자들의 BMI
[0.54644809 0.56818182 0.59171598 0.53763441 0.56497175 0.57803468]


In [ ]:
scores = np.array([88, 72, 93, 94, 89, 78, 99])
print(scores[2])
print(scores[-1])
print(scores[1:4]) # 두번째 , 세번째 , 네번째 항목을 슬라이싱
print(scores[3:]) # 마지막 인덱스를 생략 하면 디폴트 값은 -1
print(scores[4:-1]) # 마지막 인덱스로 -1을 사용할 경우 -1의 앞에 있는 78까지 슬라이싱
y = scores > 80
y
#array([False, False, True, True, True])
print(scores[scores > 80])

93
99
[72 93 94]
[94 89 78 99]
[89 78]
[88 93 94 89 99]


In [ ]:
y = [[1,2,3], [4,5,6], [7,8,9]] # 2차원 배열(리스트 자료형형)
print(y)

np_array = np.array(y) # 2차원 배열(넘파이 다차원 배열열)
np_array

np_array[0][2] 

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


3

In [ ]:
# LAB10-3
# 문자 데이터를 저장하고 있는 어떤 2차원 넘파이 배열 x에서 'c' 문자가 몇개 있는지 알고 싶다. 'c'만 추출하여 배열을 만들어라
# 그리고 다음과 같은 두 개의 2차원 배열에 정수를 담아 mat_a에서 mat_b를 뺀 결과를 확인해 봐라.
x = np.array([['a', 'b', 'c', 'd'], ['c', 'c', 'g', 'h']])
print(x [ x == 'c'])
mat_a = np.array([[10, 20, 30], [10, 20, 30]])
mat_b = np.array([[2, 2, 2], [1, 2, 3]])
print(mat_a - mat_b)

['c' 'c' 'c']
[[ 8 18 28]
 [ 9 18 27]]


In [ ]:
# LAB10-4
# 검사 대상자들의 키와 몸무게가 다음과 같이 2차원 넘파이 배열에 저장되어있다.
# x,y 그리고 z의 형태가 어떠한지 확인하고 이 정보를 바탕으로 각 대상자들의 BMI값을 저장한 배열을 생성하라
x = np.array([[1.83, 1.76, 1.69, 1.86, 1.77, 1.73], [86.0, 74.0, 59.0, 95.0, 80.0, 68.0]])
y = x[0:2, 1:3]
z = x[0:2][1:3]

print('x shape : ', x.shape)
print('y shape : ', y.shape)
print('z shape : ', z.shape)
print('z values = : ', z)
bmi = x[1] / x[0]**2
print('BMI data')
print(bmi)

x shape :  (2, 6)
y shape :  (2, 2)
z shape :  (1, 6)
z values = :  [[86. 74. 59. 95. 80. 68.]]
BMI data
[25.68007405 23.88946281 20.65754    27.45982194 25.53544639 22.72043837]


In [ ]:
# LAB10-5
# 선수들의 키와 몸무게가 하나의 리스트를 구성하고 있으며, 이들의 리스트로 이루어진 데이터 player가 있다.
players = [[170, 76.4], [183, 86.2], [181, 78.5], [176, 80.1]]
# 이를 바탕으로 넘파이 2차원 배열을 만들고, 선수들 가운데 몸무게가 80이 넘는 선수들만 골라서 정보를 추출해보고, 키가 180 이상인 선수들의 정보도 추출하자
np_players = np.array(players)
print('몸무게가 80 이상인 선수 정보')
print(np_players[ np_players[:, 1] >= 80.0])
print('키가 180 이상인 선수 정보')
print(np_players[ np_players[:, 0] >= 180.0])

몸무게가 80 이상인 선수 정보
[[183.   86.2]
 [176.   80.1]]
키가 180 이상인 선수 정보
[[183.   86.2]
 [181.   78.5]]


In [ ]:
# arange() 함수와 range()함수 비교
# 사용법은 동일

In [ ]:
# 평균, 중앙값 계산
a = np.array([3, 7, 1, 2, 21]) # 21은 전체데이터 중에서 비정상적으로 큰 값
print(np.mean(a)) # 평균
print(np.median(a)) # 중앙값 - [3, 7, 1, 2, 21]들 중 가운데 항목을 가져옴.

NameError: ignored

11장 pandas

In [ ]:
# numpy , pandas 둘다 중요하지만 pandas가 더 중요
# pandas는 엑셀을 파이썬으로 한다고 보면됨
# numpy 자료형 - 배열 array , 2차원 배열 만들 수 있음.
# list는 모든 자료형을 받을 수 있지만 array는 불가능
# pandas 자료형
# Series - index와 elements(데이터)를 가지고 있는 1차원 배열 
# 스프레드 시트에서의 column에 해당. column 하나
# Dataframe - Series들의 집합으로 이루어진 스프레드 시트를 의미.

In [1]:
import pandas as pd
import numpy as np

In [ ]:
s1 = pd.Series(['smile', 'love', 'peace'])
s1

0    smile
1     love
2    peace
dtype: object

In [ ]:
s2 = pd.Series(np.arange(5), index=['a', 'b', 'c', 'd', 'e'])
s2
print(s2['a'])
print()
print(s2[['a', 'c', 'e']]) # 여러개의 값으 indexing 할 경우, 리스트 형태로 넣어줌.

0

a    0
c    2
e    4
dtype: int64


In [13]:
#Dataframe 같은 길이의 리스트를 가지는 딕셔너리를 이용하여 생성
poli_dict = {"이름" :['박원순', '김문수', '안철수'], "정당" :['더불어민주당', '자유한국당', '바른미래당'], "기호" : [1, 2, 3]}
poli_df = pd.DataFrame(poli_dict, index = ["후보1", "후보2", "후보3"])
poli_df

이름      정당  기호
후보1  박원순  더불어민주당   1
후보2  김문수   자유한국당   2
후보3  안철수   바른미래당   3

In [14]:
print(poli_df.shape) #np.array의 shape를 반환해주는 함수
print(poli_df.ndim) # np.array의 차원의 수를 반환해주는 함수 (numver of dimension)
print(poli_df.size) # np.array의의 총 elements(원소) 개수를 반환

(3, 3)
2
9


In [ ]:
# DataFrame 인덱싱 & 슬라이싱
poli_df["이름"]

후보1    박원순
후보2    김문수
후보3    안철수
Name: 이름, dtype: object

In [ ]:
type(poli_df["이름"]) # 자료 결과값

pandas.core.series.Series

In [15]:
# DataFrame 인덱싱 & 슬라이싱
poli_df[["이름", "정당"]] # 리스트 형태로 넣어주는 것

이름      정당
후보1  박원순  더불어민주당
후보2  김문수   자유한국당
후보3  안철수   바른미래당

In [ ]:
type(poli_df[["이름", "정당"]]) # 자료 결과값

pandas.core.frame.DataFrame

In [ ]:
# DataFrame 인덱싱 & 슬라이싱
poli_df[0:2]

이름      정당  기호
후보1  박원순  더불어민주당   1
후보2  김문수   자유한국당   2

In [ ]:
poli_df["이름"][0:2]

후보1    박원순
후보2    김문수
Name: 이름, dtype: object

In [ ]:
# DataFrame 인덱싱 & 슬라이싱
# loc & iloc
# loc:index 이름으로 인덱싱
poli_df.loc["후보1"] # 해당 row 선택 

이름       박원순
정당    더불어민주당
기호         1
Name: 후보1, dtype: object

In [ ]:
poli_df["이름"].loc["후보1"]

'박원순'

In [ ]:
# loc & iloc
# loc:index number로 인덱싱 & 슬라이싱
# iloc를 주로 많이 씀.
poli_df.iloc[1:]

이름     정당  기호
후보2  김문수  자유한국당   2
후보3  안철수  바른미래당   3

In [ ]:
poli_df["정당"].iloc[:2]

후보1    더불어민주당
후보2     자유한국당
Name: 정당, dtype: object

In [ ]:
#DataFrame 컬럼 추가
poli_df["지지율"] = [60,20,20]
poli_df

이름      정당  기호  지지율
후보1  박원순  더불어민주당   1   60
후보2  김문수   자유한국당   2   20
후보3  안철수   바른미래당   3   20

In [ ]:
poli_df["당선가능성"] = np.where(poli_df["지지율"] > 40, 1, 0)
poli_df

이름      정당  기호  지지율  당선가능성
후보1  박원순  더불어민주당   1   60      1
후보2  김문수   자유한국당   2   20      0
후보3  안철수   바른미래당   3   20      0

In [ ]:
# DataFrame 컬럼 삭제
del poli_df["당선가능성"]
poli_df

이름      정당  기호  지지율
후보1  박원순  더불어민주당   1   60
후보2  김문수   자유한국당   2   20
후보3  안철수   바른미래당   3   20

In [ ]:
poli_df.drop(['기호', '지지율'], axis=1)

이름      정당
후보1  박원순  더불어민주당
후보2  김문수   자유한국당
후보3  안철수   바른미래당

In [ ]:
poli_df.drop("후보3")

이름      정당  기호  지지율
후보1  박원순  더불어민주당   1   60
후보2  김문수   자유한국당   2   20

In [ ]:
poli_df.drop(["후보2", "후보3"])

이름      정당  기호  지지율
후보1  박원순  더불어민주당   1   60

In [ ]:
#DataFrame row 삭제 
# 주의
# drop() 함수는 제거된 데이터프레임을 return 해주지 않기 때문에, 변경 된 내용을 저장하고 싶다면 새로운 객체에 할당해야 함.
# 지우고 새롭게 할당 하는 방법 
# 1. df = df.drop() 새로운 변수에 할당
# 2. df.drop( 바꿀 내용 ,inplace=기본값 false) inplace를 true로 해주면 됨.

In [ ]:
#map , apply, applymap
# Series 객체의 map 함수 존재
# map 함수를 이용하여 Series의 각 element에 원하는 함수 적용 가능
# lambda를 주로 이용!
# 데이터 변환 시 유용하게 사용 가능
s = pd.Series(np.arange(5))
s

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [ ]:
s.map(lambda x: x**2)

0     0
1     1
2     4
3     9
4    16
dtype: int64

In [ ]:
# map
# Series 객체의 map 함수 존재
# map 함수를 이용하여 Series의 각 element에 원하는 함수 적용 가능
# - 일반 함수도 사용 가능
def zero_one(x):
    result = np.where(x>2, 'a', 'b') # x가 2보다 큰 것이 참이면 a, 참이 아니라면 b로 
    return result
s.map(zero_one)    

0    b
1    b
2    b
3    a
4    a
dtype: object

In [ ]:
# map 함수를 이용하여 Series의 각 element에 원하는 함수 적용 가능
# - 함수 대신 딕셔너리를 이용하여 적용가능
change_dict = {0:"A", 1:"B", 2:"C"}
s.map(change_dict)

0      A
1      B
2      C
3    NaN
4    NaN
dtype: object

In [ ]:
# apply
# map 함수와는 다르게 Series 전체를 대상으로 원하는 함수 적용

In [ ]:
# apply
# DayaFrame의 모든 elements에 원하는 함수를 적용

In [ ]:
#pd.read_csv()
# csv 파일을 불러와 DataFrame 객체로 만들어주는 함수
# pd.read_excel(), pd.read_table(), 등등 다른 형태를 읽어오는 함수 존재 

In [ ]:
# iris_data.csv 불러오는 법
iris_df = pd.read_csv("/iris_data.csv")
iris_df

sepal.length  sepal.width  petal.length  petal.width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
iris_df.head()

sepal.length  sepal.width  petal.length  petal.width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
iris_df.shape

(150, 5)

In [ ]:
iris_mat = iris_df.values

In [ ]:
iris_mat[:4,:]

array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa']], dtype=object)

In [ ]:
print("shape:", iris_mat.shape)
print("ndim:", iris_mat.ndim)
print("size:", iris_mat.size)

shape: (150, 5)
ndim: 2
size: 750


In [ ]:
# 수치형 자료에 대한 주요 통계치를 요약해주는 함수
# describe
# 데이터 분석 초기 단계에서 , 탐색적 분석 방법으로 사용
iris_df.describe()

sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
# unique
# DataFrame의 column(Series)에 존재하는 값들의 종류를 리스트 형태로 반환시켜주는 함수
# DataFrame에 적용시키면 에러 발생 주의(column에 적용)
iris_df['class'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
iris_df['class'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 150 entries, 0 to 149
Series name: class
Non-Null Count  Dtype 
--------------  ----- 
150 non-null    object
dtypes: object(1)
memory usage: 1.3+ KB


In [ ]:
# column 별 혹은 row 별로 원하는 연산 수행
iris_df.mean(axis=0) # row방향(column별)

<ipython-input-18-31903d5030d7>:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  iris_df.mean(axis=0) # row방향(column별)


sepal.length    5.843333
sepal.width     3.054000
petal.length    3.758667
petal.width     1.198667
dtype: float64

In [ ]:
# corr, cov
# corr : 수치형 변수들 간의 상관계수를 계산해주는 함수
# cov : 수치형 변수들 간의 공분산을 계산해주는 함수
iris_df['sepal.length'].corr(iris_df['petal.width'])

0.8179536333691636

In [ ]:
# sort_values
# DataFrame의 column의 값을 기준으로 sorting 시켜주는 함수
# 여러 column을 기준으로 sort하고 싶은 경우, 리스트 형태로 입력 
iris_df.sort_values('sepal.length', ascending= True).head(3)

sepal.length  sepal.width  petal.length  petal.width        class
13           4.3          3.0           1.1          0.1  Iris-setosa
42           4.4          3.2           1.3          0.2  Iris-setosa
38           4.4          3.0           1.3          0.2  Iris-setosa

In [ ]:
iris_df.sort_values(['sepal.length', 'petal.length'], ascending= False).head(3)

sepal.length  sepal.width  petal.length  petal.width           class
131           7.9          3.8           6.4          2.0  Iris-virginica
118           7.7          2.6           6.9          2.3  Iris-virginica
117           7.7          3.8           6.7          2.2  Iris-virginica

In [ ]:
# isnull()
# DataFrame의 각 element가 null값(NaN) 인지를 boolean 형태로 돌려주는 함수
iris_df.iloc[0,0] = np.nan

In [ ]:
iris_df.isnull().head(3)

sepal.length  sepal.width  petal.length  petal.width  class
0          True        False         False        False  False
1         False        False         False        False  False
2         False        False         False        False  False

In [ ]:
# dropna()
# null 값 (NaN)이 포함된 row 혹은 column을 제거 시켜주는 함수
# 기본값으로 axix=0으로 설정
nonan_iris = iris_df.dropna()
nonan_iris.shape

(149, 5)

In [ ]:
# reset_index()


In [ ]:
# to_csv()
# DataFrame 객체를 csv파일로 저장시키는 함수
nonan_iris.to_csv("nonan_iris.csv", index=False)

In [2]:
# Groupby
# 그룹별로 연산을 지원해주는 함수
# 그룹별로 데이터를 나누고, 각 그룹에 특정 함수(연산)를 적용시킨 뒤, 그룹별 결과로 합쳐서 돌려주는 작업

In [6]:
# 산재 데이터
accident_df = pd.read_csv("/content/drive/MyDrive/work_accident.csv")
print(accident_df.shape)
accident_df.head(3)

(1811, 9)


sex  age  workPeriod  career  jobTraining  employeeNum  salary  FamilyNum  \
0    1   31           1       0            2            2     150          2   
1    2   57           2       2            2            2     160          3   
2    1   50           3       4            2            2     250          4   

   Class  
0      0  
1      0  
2      0

In [7]:
accident_df.groupby("sex").mean()

age  workPeriod    career  jobTraining  employeeNum      salary  \
sex                                                                          
1    48.443211    2.015013  1.651436     1.953655     1.858355  245.281332   
2    52.232975    2.222222  1.279570     1.931900     1.885305  130.996416   

     FamilyNum     Class  
sex                       
1     2.875979  0.362272  
2     2.720430  0.358423

In [8]:
accident_df.groupby("sex")["salary"].mean()

sex
1    245.281332
2    130.996416
Name: salary, dtype: float64

In [9]:
# Merge
# DataFrame들을 SQL 형식으로 Merge(join) 해주는 것
#  두 개의 DataFrame을 공통된 column을 통해 Merge

In [28]:
m_df1_dict = {'정당번호': [1, 2, 3, 4, 5, 6], '이름': ['더불어 민주당', '자유한국당', '바른미래당', '민주평화당', '정의당', '대한애국당'], '의원수': [121, 116, 30, 14, 6, 1]}
m_df1 = pd.DataFrame(m_df1_dict, columns=['정당번호', '이름', '의원수'])
m_df1

정당번호       이름  의원수
0     1  더불어 민주당  121
1     2    자유한국당  116
2     3    바른미래당   30
3     4    민주평화당   14
4     5      정의당    6
5     6    대한애국당    1

In [29]:
m_df2_dict = {'정당번호': [1, 2, 3, 4, 5], '지지율': [53, 12.7, 9.3, 0.6, 6.3], '의원수': ['2014-03-26','2000-03-26','2010-03-26','2004-03-26','2001-03-26']}
m_df2 = pd.DataFrame(m_df2_dict, columns=['정당번호', '지지율', '창당일'])
m_df2

정당번호   지지율  창당일
0     1  53.0  NaN
1     2  12.7  NaN
2     3   9.3  NaN
3     4   0.6  NaN
4     5   6.3  NaN

In [30]:
pd.merge(m_df1, m_df2, on='정당번호')

정당번호       이름  의원수   지지율  창당일
0     1  더불어 민주당  121  53.0  NaN
1     2    자유한국당  116  12.7  NaN
2     3    바른미래당   30   9.3  NaN
3     4    민주평화당   14   0.6  NaN
4     5      정의당    6   6.3  NaN

In [31]:
m_df2.columns = {'party_num', '지지율', '창당일'}
m_df2.head(2)

party_num   지지율  창당일
0          1  53.0  NaN
1          2  12.7  NaN

In [33]:
pd.merge(m_df1, m_df2, left_on="정당번호", right_on="party_num")

정당번호       이름  의원수  party_num   지지율  창당일
0     1  더불어 민주당  121          1  53.0  NaN
1     2    자유한국당  116          2  12.7  NaN
2     3    바른미래당   30          3   9.3  NaN
3     4    민주평화당   14          4   0.6  NaN
4     5      정의당    6          5   6.3  NaN