<a href="https://colab.research.google.com/github/Hyunfor/2023_HNU_PythonClass/blob/master/23_05_02_~_%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%82%AC%EC%9D%B4%EC%96%B8%EC%8A%A4_%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EC%88%98%EC%97%85_9(8%EC%9E%A5)_~_10_(_9%EC%9E%A5_%EC%99%84%2C_10%EC%9E%A5_%EC%A7%84%ED%96%89%2C_11%EC%9E%A5_%EC%A7%84%ED%96%89).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

8장


In [ ]:
# 딕셔너리 장점 
# 어떤 자료형도 받을 수 있다.
# 튜플은 보안상의 이유로 따로 둠

# 리스트와 튜플은 순서자료형
phone_num_list = {}
phone_num_list["전우치"] = "010-2233-4455"
print(phone_num_list)

phone_num_list["도사협회"] = "01-1133-4455"
phone_num_list["빌런협회"] = "04-7733-4455"
print(phone_num_list)

# 리스트에서 인덱스, 딕셔너리에서는 키가 있어야 값을 찾을 수 있다.
# 모든 키를 출력하려면 keys()라는 메소드를 사용
# 반면 딕셔너리에서 사용되는 모든 값을 출력하려면 values()를 사용.
# 딕셔너리 내부의 모든 값을 출력하려면 items()를 사용
# items()를 쓰면 튜플로 출력 (출력된 값)
# Key()는 [(출력된 값), (출력된 값)]
for name, phone_num in phone_num_list.items():
    print(name,':',phone_num)

{'전우치': '010-2233-4455'}
{'전우치': '010-2233-4455', '도사협회': '01-1133-4455', '빌런협회': '04-7733-4455'}
전우치 : 010-2233-4455
도사협회 : 01-1133-4455
빌런협회 : 04-7733-4455


In [ ]:
person_dic = {'Name': "홍길동", 'Age': 27, 'Class': "초급"}
print(person_dic['Name']) # 딕셔너리의 Name키로 값을 조회
print(person_dic['Age']) # 딕셔너리의 Age키로 값을 조회
print(person_dic['Class'])

홍길동
27
초급


In [ ]:
def sum(a, b): # 일반적인 함수문
    return a+b
print(sum(3,4))

sum = lambda a,b : a+b # lambda함수로 일반적인 함수 코드를 간결하게 만들 수 있음.
print(sum(3,4))

7
7


In [ ]:
f = lambda x : x**2
f(3)

9

In [ ]:
f = lambda x : x/2
f(4)


2.0

In [ ]:
even_power = lambda x : x**2 if x%2 == 0 else x
print(even_power(2))
print(even_power(3))

4
3


In [ ]:
# 심화문제 8.3 한번 풀어보기
# 학번, 이름, 전화번호의 3쌍의 요소를 가지는 student_tup라는 튜플이 존재

# 1) 튜플을 수정하여 {학번 : [이름, 전화번호]}의 쌍으로 이루어진 딕셔너리를 만들어서 출력

# 2) 학생의 학번을 입력받아서 이름과 전화번호를 출력하는 학사 정보 프로그램을 작성

# 3) student_tup의 마지막 항목으로 직전학기 학점을 추가. 세 학생의 학점은 각각 4.3, 3.9, 4.25이다. 
# 이를 바탕으로 딕셔너리를 만들어 학생 정보를 출력하라

# 4) 3)의 정보를 이용하여 for 반보문과 인덱싱을 통해서 세 학생의 학점 평균값을 다음과 같이 출력하라.

9장

In [ ]:
# 문자열도 순서자료형 - > 인덱스를 가지고 있다 & 반복문에 사용가능
# split() - > 문자열 분리
# join() - > 문자열 합치기
# replace() - > 문자열 변경
# strip() - > 공백 제거거

In [ ]:
s = 'www.booksr.co.kr'
s.find('.kr')

13

In [ ]:
s = 'www.booksr.co.kr'
s.find('x')

-1

In [ ]:
s = 'www.booksr.co.kr'
print(s.index('.kr'))

13


In [ ]:
s = 'www.booksr.co.kr'
print(s.index('x'))

ValueError: ignored

In [ ]:
# LAB 9-2
# 트위터 메시지 처리의 단어 추출
t = "There's a reason some people are working to make it harder to vote, especially for people of color. It's because when we show up, things change."
length = len(t.split(' '))
print('world count:', length)

world count: 26


In [ ]:
# 9.7 워드클라우드 내용은 스스로 학습
# 9.8 정규표현식 내용은 프로젝트 진행시 필요시 학습

In [ ]:
# 심화문제 9.1 9.5, 9.6 집에서 해보기

In [ ]:
# 심화문제 9.1
# 영문 이름을 입력받은 후 중간 이름을 출력하라
name = input("영문 이름을 입력하세요: ")
names_list = name.split()  # 공백을 기준으로 문자열을 단어 단위로 분리합니다.
num_names = len(names_list)  # 입력된 이름의 단어 개수를 구합니다.

# 입력된 이름이 두 개 이상의 단어로 이루어져 있다면 중간 단어를 출력합니다.
if num_names >= 2:
    middle_index = num_names // 2  # 중간 단어의 인덱스를 계산합니다.
    middle_name = names_list[middle_index]  # 중간 단어를 가져옵니다.
    print("중간 이름은", middle_name, "입니다.")
else:
    print("입력된 이름이 너무 짧습니다.")

영문 이름을 입력하세요: jon smths meguel
중간 이름은 smths 입니다.


In [ ]:
# 심화문제 9.5
# s = Korea is awesome! I REALLY LOVE KOREA.
# Korea가 몇번 나타나는가 출력하라. 이때 KOREA, Korea와 korea는 같은 문자열로 간주한다.
s = "Korea is awesome! I REALLY LOVE KOREA."
count = s.lower().count("korea")  # 대소문자를 구분하지 않고 "Korea"가 몇 번 나타나는지 계산합니다.
print("Korea가 총", count, "번 나타납니다.")

Korea가 총 2 번 나타납니다.


In [ ]:
# 심화문제 9.6
# 문장에 'English = 98'와 같이 과목점수가 저장되어 있다. 이문장을 분석하여 숫자로 이루어진 점수를 읽어서 합과 평균점수를 구하라
# 문장 s : English = 89, Science = 90, Math = 92, History = 80.
# 총점 : 351
# 평균점수 87.75
s = "English = 89, Science = 90, Math = 92, History = 80."
scores = []  # 점수를 저장할 리스트를 초기화합니다.
for item in s.split(","):  # 쉼표를 기준으로 문자열을 분리합니다.
    score = item.split("=")[-1].strip()  # 등호를 기준으로 문자열을 분리하여 숫자를 추출합니다.
    scores.append(int(score))  # 추출한 숫자를 정수형으로 변환하여 리스트에 추가합니다.
total = sum(scores)  # 총점을 계산합니다.
average = total / len(scores)  # 평균점수를 계산합니다.
print("총점:", total)
print("평균점수:", round(average, 2))

ValueError: ignored

In [ ]:
s = "English = 89, Science = 90, Math = 92, History = 80."
scores = []
for item in s.split(","):
    score = item.split("=")[-1].strip()
    scores.append(float(score))  # 정수 대신 실수로 변환합니다.
total = sum(scores)
average = total / len(scores)
print("총점:", total)
print("평균점수:", round(average, 2))

총점: 351.0
평균점수: 87.75


10장
numpy

In [ ]:
# numpy의 핵심적인 객체는 다차원 배열
# 2차원 배열(테이블)을 넘파이를 이용해서 생성
# 배열의 각 요소는 index라 불리는 정수들로 참조
# 넘파이에서 차원은 axis 축 이라고도 함
# 행이 0, 축이 1

In [ ]:
import numpy as np

In [ ]:
mid_scores = np.array([10, 20, 30])
final_scores = np.array([60, 70, 80])
total = mid_scores + final_scores
print('시험성적의 합계 : ', total) # 각 요소별 합계가 나타난다
print(type(mid_scores))
print('시험성적의 평균 : ', total/2) # 모든 요소를 2로 나눈다
print(type(final_scores))

시험성적의 합계 :  [ 70  90 110]
<class 'numpy.ndarray'>
시험성적의 평균 :  [35. 45. 55.]
<class 'numpy.ndarray'>


In [ ]:
a = np.array([1, 2, 3])
print(a.shape)# 객체의 형태
print(a.ndim) # 객채의 차원
print(a.dtype) # 객체의 내부 자료형
print(a.itemsize) # 객체 내부 자료형이 차지하는 메모리 크기
print(a.size) # 객체의 전체 크기(항목 수수)

(3,)
1
int64
8
3


In [ ]:
# 넘파이의 배열, broadcasting브로드캐스팅이라 함함

In [ ]:
# LAB10-2 해보기
# 넘파이를 이용하여 다수의 인원에 대해 BMI 계싼을 효율적으로 적용하자
# 키를 저장하는 리스트 heights, 다른 하나는 몸무게를 저장하는 weights
# BMI를 한번에 계산 할 수 있는 방법은 ? 
heights = [1.83, 1.76, 1.69, 1.86, 1.77, 1.73]
weights = [86, 74, 59, 95, 80, 68]

np_heights = np.array(heights)
np_weights = np.array(weights)

bmi = np_heights/(np_heights**2)
print('대상자들의 키: ', np_heights)
print('대상자들의 몸무게: ', np_weights)
print('대상자들의 BMI')
print(bmi)

대상자들의 키:  [1.83 1.76 1.69 1.86 1.77 1.73]
대상자들의 몸무게:  [86 74 59 95 80 68]
대상자들의 BMI
[0.54644809 0.56818182 0.59171598 0.53763441 0.56497175 0.57803468]


In [ ]:
scores = np.array([88, 72, 93, 94, 89, 78, 99])
print(scores[2])
print(scores[-1])
print(scores[1:4]) # 두번째 , 세번째 , 네번째 항목을 슬라이싱
print(scores[3:]) # 마지막 인덱스를 생략 하면 디폴트 값은 -1
print(scores[4:-1]) # 마지막 인덱스로 -1을 사용할 경우 -1의 앞에 있는 78까지 슬라이싱
y = scores > 80
y
#array([False, False, True, True, True])
print(scores[scores > 80])

93
99
[72 93 94]
[94 89 78 99]
[89 78]
[88 93 94 89 99]


In [ ]:
y = [[1,2,3], [4,5,6], [7,8,9]] # 2차원 배열(리스트 자료형형)
print(y)

np_array = np.array(y) # 2차원 배열(넘파이 다차원 배열열)
np_array

np_array[0][2] 

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


3

In [ ]:
# LAB10-3
# 문자 데이터를 저장하고 있는 어떤 2차원 넘파이 배열 x에서 'c' 문자가 몇개 있는지 알고 싶다. 'c'만 추출하여 배열을 만들어라
# 그리고 다음과 같은 두 개의 2차원 배열에 정수를 담아 mat_a에서 mat_b를 뺀 결과를 확인해 봐라.
x = np.array([['a', 'b', 'c', 'd'], ['c', 'c', 'g', 'h']])
print(x [ x == 'c'])
mat_a = np.array([[10, 20, 30], [10, 20, 30]])
mat_b = np.array([[2, 2, 2], [1, 2, 3]])
print(mat_a - mat_b)

['c' 'c' 'c']
[[ 8 18 28]
 [ 9 18 27]]


In [ ]:
# LAB10-4
# 검사 대상자들의 키와 몸무게가 다음과 같이 2차원 넘파이 배열에 저장되어있다.
# x,y 그리고 z의 형태가 어떠한지 확인하고 이 정보를 바탕으로 각 대상자들의 BMI값을 저장한 배열을 생성하라
x = np.array([[1.83, 1.76, 1.69, 1.86, 1.77, 1.73], [86.0, 74.0, 59.0, 95.0, 80.0, 68.0]])
y = x[0:2, 1:3]
z = x[0:2][1:3]

print('x shape : ', x.shape)
print('y shape : ', y.shape)
print('z shape : ', z.shape)
print('z values = : ', z)
bmi = x[1] / x[0]**2
print('BMI data')
print(bmi)

x shape :  (2, 6)
y shape :  (2, 2)
z shape :  (1, 6)
z values = :  [[86. 74. 59. 95. 80. 68.]]
BMI data
[25.68007405 23.88946281 20.65754    27.45982194 25.53544639 22.72043837]


In [ ]:
# LAB10-5
# 선수들의 키와 몸무게가 하나의 리스트를 구성하고 있으며, 이들의 리스트로 이루어진 데이터 player가 있다.
players = [[170, 76.4], [183, 86.2], [181, 78.5], [176, 80.1]]
# 이를 바탕으로 넘파이 2차원 배열을 만들고, 선수들 가운데 몸무게가 80이 넘는 선수들만 골라서 정보를 추출해보고, 키가 180 이상인 선수들의 정보도 추출하자
np_players = np.array(players)
print('몸무게가 80 이상인 선수 정보')
print(np_players[ np_players[:, 1] >= 80.0])
print('키가 180 이상인 선수 정보')
print(np_players[ np_players[:, 0] >= 180.0])

몸무게가 80 이상인 선수 정보
[[183.   86.2]
 [176.   80.1]]
키가 180 이상인 선수 정보
[[183.   86.2]
 [181.   78.5]]


In [ ]:
# arange() 함수와 range()함수 비교
# 사용법은 동일

In [ ]:
# 평균, 중앙값 계산
a = np.array([3, 7, 1, 2, 21]) # 21은 전체데이터 중에서 비정상적으로 큰 값
print(np.mean(a)) # 평균
print(np.median(a)) # 중앙값 - [3, 7, 1, 2, 21]들 중 가운데 항목을 가져옴.

6.8
3.0


11장 pandas

In [10]:
# numpy , pandas 둘다 중요하지만 pandas가 더 중요
# pandas는 엑셀을 파이썬으로 한다고 보면됨
# numpy 자료형 - 배열 array , 2차원 배열 만들 수 있음.
# list는 모든 자료형을 받을 수 있지만 array는 불가능
# pandas 자료형
# Series - index와 elements(데이터)를 가지고 있는 1차원 배열 
# 스프레드 시트에서의 column에 해당. column 하나
# Dataframe - Series들의 집합으로 이루어진 스프레드 시트를 의미.

In [3]:
import pandas as pd
import numpy as np

In [9]:
s1 = pd.Series(['smile', 'love', 'peace'])
s1

0    smile
1     love
2    peace
dtype: object

In [12]:
s2 = pd.Series(np.arange(5), index=['a', 'b', 'c', 'd', 'e'])
s2
print(s2['a'])
print()
print(s2[['a', 'c', 'e']]) # 여러개의 값으 indexing 할 경우, 리스트 형태로 넣어줌.

0

a    0
c    2
e    4
dtype: int64


In [15]:
#Dataframe 같은 길이의 리스트를 가지는 딕셔너리를 이용하여 생성
poli_dict = {"이름" :['박원순', '김문수', '안철수'], "정당" :['더불어민주당', '자유한국당', '바른미래당'], "기호" : [1, 2, 3]}
poli_df = pd.DataFrame(poli_dict, index = ["후보1", "후복2", "후보3"])
poli_df

이름      정당  기호
후보1  박원순  더불어민주당   1
후복2  김문수   자유한국당   2
후보3  안철수   바른미래당   3